### PR TITLE
#add SCSS-Library

### PR DESCRIPTION
**Pull request by MoniqueHahnefeld**
fertig :) !!!

### CODE REVIEW

**Comment by may17** [comment]
Thx for the work. We have to discuss it. In my opinion the solution is oversized for beginners.

**Comment by MoniqueHahnefeld** [comment]
ok, then maybe we can make an advanced branch for not beginners :D 
let's discuss. what do you think should be easier?

**Comment by may17** [comment]
@MoniqueHahnefeld why should we have two versions? It`s just a demo :) I think you misunderstood the goal of the cod. The cod is not a startpoint for advanced developers to create there websites on it. Just take a look into the license and you will see why this makes no sense.

With the current release today, we`ve added scss support and that`s a huge step in the right direction.

Perhaps there will be new requirements  with a cod 2.0. We will see :)

**Comment by ciaobello** [comment]
Thx for integrating the SCSS into COD.
I'm happy to have this topic as notification on Github, so i cold following what happened.  I tried to play around with COD on 3.5.2. I was surprised when i tried to change the variables (They still appear in the settings of the Theme) and yes, of course i tried to change them there :), till I realized and remembered when we do include external CSS the variables in the settings of themes not work anymore because they bypass the internal Contao CSS engine/editor.
So with other words I'm agree with MoniqueHahnefeld if she worries about **newbies/not experts** to give the chance to use the Theme the old fashion way and or some hints where to start with SCSS. I do not ask you to write a manual, just begging to give one or two links with info how to start dealing with SCSS that we (community)/I could do some more research to publish after 2 ways, how to work with COD. With and without SCSS (I think that's why the variables are still visible on the old place?!).
Important would be to get the info how Contao leads with this SCSS files and what would be necessary to to change them that everything works fine ...

Thx again. 

btw. the variables i could change  here (see path) and it worked out of the box (I just changed color values):
**/theme/scss/_variables.scss** . And yes I also understood how the Import from the other sections work
(**/files/contaodemo/theme/scss/theme-styles.min.scss**).
My main doubt is, how deals Contao with the SCSS and what is needed to change it without messing up the way how contao needs/wants it. Probably it just needs some keywords where we/I can look after on google;)

**Comment by may17** [comment]
@ciaobello thx for your input. Let me summarise:

We need two things. 1. An introduction how to customize the cod and 2. a generell scss introduction to scss with contao.

Todo no. 1 is a job for the cod team but todo no. 2 is something that should find it`s place on the contao website.

The variables in the theme backend must be removed in a further version. That`s my fault sorry for that.

**Comment by ciaobello** [comment]
Yes, how to customize SCSS (within contao) and if there is a difference between a "normal way" (static website) and within Contao (because of external parser script etc.)

2) ok. so we do.

**Comment by ciaobello** [comment]
I guess i already have enough to read for the weekend:
http://www.mediendepot-ruhr.de/sassscss-und-compass-als-css-preprocessor.html

**Pull request closed without merging**
