### PR TITLE
Update to Contao 4.4

### LINKED ISSUE #76: COD nach Contao 4.x portieren

### PR DESCRIPTION
**Pull request by cliffparnitzky**
Closes #76

### CODE REVIEW

**Comment by Toflar** [comment]
Who's merging here? Works perfectly fine for me, thank you @cliffparnitzky

**Comment by may17** [comment]
@cliffparnitzky is now official part of the cod team. I think this should be his honor :D

**Comment by cliffparnitzky** [comment]
Done :smile:

**Comment by cliffparnitzky** [comment]
Tagged as v4.0.0

**Pull request merged**
